#ifndef __READ_H__
#define __READ_H__

#include <stdlib.h>

typedef struct {
	int length;	/*< short read length */
	size_t id;	/* read identifier */

	char *identifier;
	char *sequence;	/*< literal read sequence */
	char *qscore;	/*< quality score associated with a read */
} read_t;

/* Functions for short READs generated by genome sequencer */
static inline read_t *read_create()
{
	read_t *tmp_read = (read_t *) malloc(sizeof(*tmp_read));
	if (tmp_read == NULL) {
		return NULL;
	}

	tmp_read->length = 0;
	tmp_read->sequence = NULL;
	tmp_read->qscore = NULL;
	tmp_read->identifier = NULL; 

	return tmp_read;
}

static inline void read_destroy(read_t *tmp_read)
{
	free(tmp_read);
}

#endif
